# Generated by Django 5.2.8 on 2025-11-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='story',
            name='api_story_user_id_5fb8c1_idx',
        ),
        migrations.RemoveIndex(
            model_name='story',
            name='api_story_expires_d6713a_idx',
        ),
        migrations.AlterField(
            model_name='story',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
